# Generated by Django 5.2.6 on 2025-11-28 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_topics_note_save_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='save',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='like',
            name='student',
            field=models.ForeignKey(db_column='std_id', on_delete=django.db.models.deletion.CASCADE, related_name='liked_topics', to='users.students'),
        ),
        migrations.AlterField(
            model_name='like',
            name='topic',
            field=models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='users.topics'),
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(db_column='std_id', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.students'),
        ),
    ]
