# Generated by Django 5.2.8 on 2025-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_like_options_alter_note_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
