# Generated by Django 5.2.6 on 2025-12-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_topic_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'managed': False, 'ordering': ['title'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
