# Generated by Django 5.2.6 on 2025-12-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_topic_delete_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='text',
        ),
    ]
