# Generated by Django 5.2.6 on 2025-12-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
