# Generated by Django 5.2.6 on 2025-11-28 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admins_alter_students_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_content', models.TextField()),
                ('topic_title', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.students')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_topics', to='users.students')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='users.topics')),
            ],
            options={
                'db_table': 'saves',
                'unique_together': {('student', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_topics', to='users.students')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='users.topics')),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
