# Generated by Django 5.2.6 on 2025-12-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_topic_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('link_title', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name': 'External Resource',
                'verbose_name_plural': 'External Resources',
                'db_table': 'external_resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LearningUnlock',
            fields=[
                ('unlock_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_item', models.TextField()),
            ],
            options={
                'verbose_name': 'Learning Unlock Item',
                'verbose_name_plural': 'Learning Unlock Items',
                'db_table': 'learning_unlocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RealWorldMagic',
            fields=[
                ('magic_id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('card_title', models.CharField(max_length=255)),
                ('card_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Real-World Magic Point',
                'verbose_name_plural': 'Real-World Magic Points',
                'db_table': 'real_world_magic',
                'managed': False,
            },
        ),
    ]
