# Generated by Django 5.2.6 on 2025-11-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_save_options_alter_like_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'managed': False},
        ),
    ]
